CREATE TABLE IF NOT EXISTS products (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL, category TEXT NOT NULL,
 price INTEGER NOT NULL CHECK(price > 0), compare_price INTEGER NOT NULL DEFAULT 0,
 fabric TEXT NOT NULL, description TEXT NOT NULL,
 sizes TEXT NOT NULL, images TEXT NOT NULL,
 active INTEGER NOT NULL DEFAULT 1, illustration INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS login_limit (id INTEGER PRIMARY KEY CHECK(id=1), failures INTEGER NOT NULL, blocked_until INTEGER NOT NULL);
INSERT OR IGNORE INTO login_limit VALUES (1,0,0);
